### ISSUE TITLE
Holding shift then clicking Choose APK doesn't do anything different, leaving me unable to create downgrade patches

### ISSUE THREAD

**Issue by eeveeishpowered** [ComputerElite/wiki#2]
Title explains it all.
The wiki says that you can hold down shift whilst clicking Choose APK to select 2 apks to create a downgrade patch for. That isn't the case for me.
I would love to send a video showcasing what happens for me but I don't know how to visualise keyboard inputs on-screen.

**Comment by ComputerElite** [comment]
hmm. It has been working for me all the time. Are you sure your're pressing shift and not caps lock?

**Comment by eeveeishpowered** [comment]
Just realised that whilst holding shift you need to select the first apk then the second apk, instead of just selecting them both in one prompt (which I'm kinda used to) so I'll close this issue. As a feature request, maybe make it more obvious that holding shift allows you to create a patch?

**Comment by eeveeishpowered** [comment]
Whilst I'm here, is there any way I can upload a patch?

**Comment by ComputerElite** [comment]
Sure create an pull request or open an issue with the version part from the json
